### Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.
#### Задача 1
Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]

scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [1]:
import numpy as np
import pandas as pd

In [2]:
salary = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
scoring = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
df = pd.DataFrame([np.transpose(salary), np.transpose(scoring)], index=['salary', 'scoring']).T
df

salary  scoring
0      35      401
1      45      574
2     190      874
3     200      919
4      40      459
5      70      739
6      54      653
7     150      902
8     120      746
9     110      832

1. Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с помощью функции numpy.cov. Полученные значения должны быть равны.

In [3]:
((df['salary'] - df['salary'].mean())*(df['scoring'] - df['scoring'].mean())).mean()


9157.84

In [4]:
(df['salary']*df['scoring']).mean()-df['salary'].mean()*df['scoring'].mean()

9157.839999999997

In [5]:
np.cov(df['salary'], df['scoring'], ddof=False)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

unbias

In [6]:
((df['salary'] - df['salary'].mean())*(df['scoring'] - df['scoring'].mean())).sum()/(df.shape[0]-1)

10175.37777777778

In [7]:
np.cov(df['salary'], df['scoring'], ddof=True)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [8]:
df.cov()

salary       scoring
salary    3882.933333  10175.377778
scoring  10175.377778  33854.322222

2. Найдите коэффициент корреляции Пирсона: с помощью ковариации и средних квадратических отклонений двух признаков, а затем с помощью специальных функций из библиотек numpy и pandas.

In [9]:
np.cov(salary, scoring, ddof=False)[0][1]/(salary.std()*scoring.std())

0.8874900920739162

In [10]:
df.corr()

salary  scoring
salary   1.00000  0.88749
scoring  0.88749  1.00000

In [11]:
np.corrcoef(salary, scoring)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

#### Задача 2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111

Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [12]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
pd.DataFrame(IQ, columns=['IQ']).describe()

IQ
count   10.000000
mean   118.100000
std     10.545668
min     99.000000
25%    112.000000
50%    118.500000
75%    125.000000
max    131.000000

In [13]:
IQ.std(ddof=1)

10.54566788359614

Доверительный интервал 95% будет +-2 сигмы от среднего

In [14]:
print(f"({IQ.mean()- 2*IQ.std(ddof=1)}, {IQ.mean()+ 2*IQ.std(ddof=1)})")

(97.00866423280772, 139.19133576719227)


#### Задача 3

Известно, что рост футболистов в сборной распределен нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

t(1-0.05/2, 26) = 1.706 - но нам это не пригодится, т.к. известна дисперсия?

In [15]:
D = 25
n = 27
M = 174.2
#t = 1.706
S = np.sqrt(D)
print(f'({M-2*S/np.sqrt(n)}, {M+2*S/np.sqrt(n)})')

(172.27549910270125, 176.12450089729873)


#### Задача 4

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию.

ничего креативного не могу придумать кроме предсказания сборов на основе информации, известной ДО релиза. (режиссер, главные роли, бюджет, год выпуска и т.п.)